[package]
name = "osmtc2mongo"
version = "0.1.0"
authors = ["Pascal Rhod <pascal.rhod@canaltp.fr>"]

[dependencies]
docopt = "0.7"
rustc-serialize = "0.3"
csv = "0.15"
osmpbfreader = "0.9"
wkt = "0.0.6"
