[package]
name = "osm_transit_extractor"
version = "0.1.0"
authors = ["Pascal Rhod <pascal.rhod@canaltp.fr>", "Noémie Lehuby <noemie.lehuby@canaltp.fr>"]

[dependencies]
csv = "1.0.0-beta.4"
osmpbfreader = "0.9"
wkt = "0.0.6"
serde = "1.0.12"
serde_derive = "1.0.12"
structopt = "0.1.0"
structopt-derive = "0.1"
